export const customTabs = [
    {
        "id": 1,
        "text": "Backlog",
        "count": 1000,
    },
    {
        "id": 2,
        "text": "Pending",
        "count": 0,
    },
    {
        "id": 3,
        "text": "Final Sign-Off",
        "count": 0,
    }
]

export const sidebarTabData = {
    "Backlog": [{
        stackId: 100000,
        checked: true,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY23Q2',
        specialRequirement: 750,
        histForecastPercent: 88,
        futureForecastPercent: 87,
    },
    {
        stackId: 100001,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 58,
        futureForecastPercent: 82,
        confidenceInterval: 'FY24Q2',
        specialRequirement: 710,
    },
    {
        stackId: 100002,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 92,
        futureForecastPercent: 81,
        confidenceInterval: 'FY24Q2',
        specialRequirement: 350,
    },
    {
        stackId: 100003,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 88,
        futureForecastPercent: 87,
        confidenceInterval: 'FY22Q2',
        specialRequirement: 790,
    },
    {
        stackId: 100004,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 88,
        futureForecastPercent: 37,
        confidenceInterval: 'FY21Q2',
        specialRequirement: 550,
    },
    {
        stackId: 100005,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 18,
        futureForecastPercent: 87,
        confidenceInterval: 'FY22Q2',
        specialRequirement: 400,
    },
    {
        stackId: 100006,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 88,
        futureForecastPercent: 81,
        confidenceInterval: 'FY22Q1',
        specialRequirement: 900,
    },
    {
        stackId: 100007,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 68,
        futureForecastPercent: 87,
        confidenceInterval: 'FY25Q1',
        specialRequirement: 1000,
    },
    {
        stackId: 100008,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 81,
        futureForecastPercent: 87,
        confidenceInterval: 'FY23Q2',
        specialRequirement: 750,
    },
    {
        stackId: 100009,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        histForecastPercent: 18,
        futureForecastPercent: 87,
        confidenceInterval: 'FY23Q2',
        specialRequirement: 790,
    }],
    "Pending": [{
        stackId: 110000,
        histForecastPercent: 18,
        futureForecastPercent: 87,
        checked: true,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY25Q2',
        specialRequirement: 550,
    },
    {
        stackId: 110001,
        histForecastPercent: 28,
        futureForecastPercent: 87,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY23Q1',
        specialRequirement: 450,
    },
    {
        stackId: 110002,
        histForecastPercent: 98,
        futureForecastPercent: 81,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY22Q2',
        specialRequirement: 710,
    },
    {
        stackId: 110003,
        histForecastPercent: 78,
        futureForecastPercent: 87,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY21Q2',
        specialRequirement: 350,
    },
    {
        stackId: 110004,
        histForecastPercent: 18,
        futureForecastPercent: 57,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY22Q1',
        specialRequirement: 350,
    },
    {
        stackId: 110005,
        histForecastPercent: 99,
        futureForecastPercent: 87,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY23Q4',
        specialRequirement: 710,
    }],
    "Final Sign-Off": [{
        stackId: 120000,
        histForecastPercent: 98,
        futureForecastPercent: 11,
        checked: true,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY21Q2',
        specialRequirement: 150,
    },
    {
        stackId: 120001,
        histForecastPercent: 78,
        futureForecastPercent: 91,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY22Q2',
        specialRequirement: 780,
    },
    {
        stackId: 120002,
        histForecastPercent: 88,
        futureForecastPercent: 11,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY21Q4',
        specialRequirement: 150,
    },
    {
        stackId: 120003,
        histForecastPercent: 78,
        futureForecastPercent: 54,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY23Q2',
        specialRequirement: 750,
    },
    {
        stackId: 120004,
        histForecastPercent: 88,
        futureForecastPercent: 91,
        checked: false,
        value1: "F'CAST STAB",
        value2: "F'CAST ACC",
        confidenceInterval: 'FY22Q2',
        specialRequirement: 250,
    }]
}