export const graphData = [
  {
    id: 1,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 280,
        histFinalForecast: 500,
        consumption: 280,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 510,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 300,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 100,
        histFinalForecast: 200,
        consumption: 200,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 2,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 250,
        histFinalForecast: 750,
        consumption: 100,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 310,
        histFinalForecast: 140,
        consumption: 910,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 260,
        histFinalForecast: 310,
        consumption: 920,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 100,
        histFinalForecast: 600,
        consumption: 200,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 600,
        histFinalForecast: 270,
        consumption: 641,
        aiForecast: null,
        finalForecast: 630,
        prevQtrForecast: 910,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 400,
        histFinalForecast: 900,
        consumption: 1000,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 3,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 280,
        histFinalForecast: 500,
        consumption: 280,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 510,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 300,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 340,
        histFinalForecast: 110,
        consumption: 980,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 4,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 280,
        histFinalForecast: 500,
        consumption: 280,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 510,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 300,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 331,
        histFinalForecast: 980,
        consumption: 910,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 5,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 150,
        consumption: 500,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 210,
        histFinalForecast: 100,
        consumption: 980,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 310,
        consumption: 900,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 100,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 345,
        histFinalForecast: 542,
        consumption: 981,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 6,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 280,
        histFinalForecast: 500,
        consumption: 280,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 510,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 300,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 340,
        histFinalForecast: 340,
        consumption: 780,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 7,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 150,
        consumption: 500,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 210,
        histFinalForecast: 100,
        consumption: 980,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 310,
        consumption: 900,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 100,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 123,
        histFinalForecast: 345,
        consumption: 678,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 8,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 280,
        histFinalForecast: 500,
        consumption: 280,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 510,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 300,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: 320,
        histFinalForecast: 780,
        consumption: 1000,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 9,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 150,
        consumption: 500,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 210,
        histFinalForecast: 100,
        consumption: 980,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 310,
        consumption: 900,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 100,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 10,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 280,
        histFinalForecast: 500,
        consumption: 280,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 510,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 300,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 11,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 150,
        consumption: 500,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 210,
        histFinalForecast: 100,
        consumption: 980,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 310,
        consumption: 900,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 100,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 12,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 280,
        histFinalForecast: 500,
        consumption: 280,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 510,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 300,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
  {
    id: 13,
    data: [
      {
        quarter: "FY22Q1",
        histAiForecast: 200,
        histFinalForecast: 150,
        consumption: 500,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q2",
        histAiForecast: 210,
        histFinalForecast: 100,
        consumption: 980,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },

      {
        quarter: "FY22Q3",
        histAiForecast: 230,
        histFinalForecast: 310,
        consumption: 900,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY22Q4",
        histAiForecast: 700,
        histFinalForecast: 500,
        consumption: 100,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q1",
        histAiForecast: 900,
        histFinalForecast: 230,
        consumption: 640,
        aiForecast: null,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY23Q2",
        histAiForecast: 230,
        histFinalForecast: 660,
        consumption: 110,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q3",
        histAiForecast: 110,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY23Q4",
        histAiForecast: 200,
        histFinalForecast: 500,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q1",
        histAiForecast: 200,
        histFinalForecast: 550,
        consumption: 400,
        aiForecast: null,
        finalForecast: null,
        prevQtrForecast: null,
      },
      {
        quarter: "FY24Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 540,
        prevQtrForecast: 100,
      },

      {
        quarter: "FY24Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 250,
        finalForecast: 100,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY24Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 700,
        finalForecast: 220,
        prevQtrForecast: 100,
      },
      {
        quarter: "FY25Q1",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 110,
        finalForecast: 650,
        prevQtrForecast: 900,
      },
      {
        quarter: "FY25Q2",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 120,
        prevQtrForecast: 400,
      },
      {
        quarter: "FY25Q3",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 290,
        finalForecast: 500,
        prevQtrForecast: 800,
      },
      {
        quarter: "FY25Q4",
        histAiForecast: null,
        histFinalForecast: null,
        consumption: null,
        aiForecast: 200,
        finalForecast: 500,
        prevQtrForecast: 400,
      },
    ],
  },
];
